# Generated by Django 3.2.9 on 2021-11-10 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20211110_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default='BMW', on_delete=django.db.models.deletion.CASCADE, related_name='Article', to='news.category'),
        ),
    ]
