# Generated by Django 3.2.9 on 2021-11-10 09:08

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='news.category'),
        ),
    ]
