# Generated by Django 3.2.9 on 2021-11-10 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
