# Generated by Django 3.2.9 on 2021-11-13 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_auto_20211110_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='catefory_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='category_name',
            field=models.CharField(default='-', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
