# Generated by Django 3.2.9 on 2021-11-13 20:45

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_rename_catefory_id_article_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='No-image', max_length=300, null=True, upload_to=news.models.upload_image_path),
        ),
    ]
