# Generated by Django 3.2.9 on 2021-11-14 18:13

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_article_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to=news.models.upload_image_path),
        ),
    ]
