# Generated by Django 3.2.9 on 2021-11-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.TextField(default='-'),
        ),
    ]
