# Generated by Django 3.2.9 on 2021-11-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='facebook',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='main',
            name='twitter',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='main',
            name='youtube',
            field=models.TextField(default=''),
        ),
    ]
