# Generated by Django 3.2.9 on 2021-11-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211110_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='main',
            name='links',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='main',
            name='telephone',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='main',
            name='facebook',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='twitter',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='youtube',
            field=models.CharField(default='', max_length=30),
        ),
    ]
